# Generated by Django 5.0.3 on 2026-06-13 22:00

import musica.models.cancion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cancion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre de la canción')),
                ('detalle', models.TextField(blank=True, null=True, verbose_name='Detalle o descripción')),
                ('archivo', models.FileField(help_text='Sube el archivo de música (.mp3, .wav, .m4a)', upload_to=musica.models.cancion.cancion_archivo_upload_path, verbose_name='Archivo de audio')),
                ('duracion', models.FloatField(blank=True, null=True, verbose_name='Duración (segundos)')),
                ('tamano', models.IntegerField(blank=True, null=True, verbose_name='Tamaño (bytes)')),
                ('formato', models.CharField(blank=True, max_length=50, null=True, verbose_name='Formato')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Canción',
                'verbose_name_plural': 'Canciones',
                'db_table': 'canciones',
                'ordering': ['-created_at'],
            },
        ),
    ]
