# Generated by Django 5.0.3 on 2026-06-14 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musica', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancion',
            name='deleted_at',
            field=models.DateTimeField(blank=True, default=None, help_text='Si tiene valor, el registro está soft-deleted', null=True, verbose_name='Fecha de eliminación'),
        ),
    ]
