# Generated by Django 5.0.3 on 2026-06-14 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musica', '0003_cancion_deleted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancion',
            name='publicado',
            field=models.BooleanField(default=False, help_text='Indica si la canción es pública para los fans', verbose_name='Publicado'),
        ),
    ]
