# Generated by Django 5.0.3 on 2026-03-29 01:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Liquidacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, help_text='Si tiene valor, el registro está soft-deleted', null=True, verbose_name='Fecha de eliminación')),
                ('monto_total_ventas', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto total de ventas')),
                ('monto_comision_plataforma', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto comisión plataforma')),
                ('monto_pago_organizador', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto pago al organizador')),
                ('referencia_bancaria', models.CharField(blank=True, help_text='Referencia de la transferencia bancaria', max_length=255, null=True, verbose_name='Referencia bancaria')),
                ('estado', models.CharField(default='pendiente', help_text='pendiente, procesando, completado, fallido', max_length=50, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('evento', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='liquidacion', to='eventos.evento', verbose_name='Evento')),
            ],
            options={
                'verbose_name': 'Liquidación',
                'verbose_name_plural': 'Liquidaciones',
                'db_table': 'liquidaciones',
            },
        ),
    ]
