# Generated by Django 5.0.3 on 2026-06-13 22:00

import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import usuarios.models.artista
import usuarios.models.usuario
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, help_text='Si tiene valor, el registro está soft-deleted', null=True, verbose_name='Fecha de eliminación')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre completo')),
                ('ci', models.CharField(max_length=20, unique=True, verbose_name='Cédula de identidad')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Persona',
                'verbose_name_plural': 'Personas',
                'db_table': 'personas',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, help_text='Si tiene valor, el registro está soft-deleted', null=True, verbose_name='Fecha de eliminación')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Correo electrónico')),
                ('foto', models.ImageField(blank=True, help_text='Avatar del usuario. Se guarda en media/usuarios/fotos/ o en MinIO/S3.', null=True, upload_to=usuarios.models.usuario.usuario_foto_upload_path, verbose_name='Foto de perfil')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('persona', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuario', to='usuarios.persona', verbose_name='Persona')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'usuarios',
                'permissions': [('gestionar_eventos', 'Puede crear, editar y eliminar eventos'), ('verificar_tickets', 'Puede escanear y verificar tickets en el acceso'), ('gestionar_artistas', 'Puede administrar perfiles de artistas'), ('ver_reportes', 'Puede ver reportes financieros y de ventas')],
            },
        ),
        migrations.CreateModel(
            name='Artista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, help_text='Si tiene valor, el registro está soft-deleted', null=True, verbose_name='Fecha de eliminación')),
                ('nombre_artistico', models.CharField(max_length=255, verbose_name='Nombre artístico')),
                ('biografia', models.TextField(blank=True, null=True, verbose_name='Biografía')),
                ('foto', models.ImageField(blank=True, help_text='Imagen de perfil del artista. Se guarda en media/artistas/fotos/', null=True, upload_to=usuarios.models.artista.artista_foto_upload_path, verbose_name='Foto del artista')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('generos_musicales', models.ManyToManyField(blank=True, db_table='artista_genero_musical', related_name='artistas', to='eventos.generomusical', verbose_name='Géneros musicales')),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perfil_artista', to=settings.AUTH_USER_MODEL, verbose_name='Usuario vinculado')),
            ],
            options={
                'verbose_name': 'Artista',
                'verbose_name_plural': 'Artistas',
                'db_table': 'artistas',
            },
        ),
        migrations.CreateModel(
            name='Promotor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, help_text='Si tiene valor, el registro está soft-deleted', null=True, verbose_name='Fecha de eliminación')),
                ('razon_social', models.CharField(max_length=255, verbose_name='Razón social')),
                ('nit_rfc', models.CharField(max_length=50, verbose_name='NIT/RFC')),
                ('banco_nombre', models.CharField(max_length=100, verbose_name='Nombre del banco')),
                ('cuenta_bancaria', models.CharField(max_length=50, verbose_name='Cuenta bancaria')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_promotor', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Promotor',
                'verbose_name_plural': 'Promotores',
                'db_table': 'promotores',
            },
        ),
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, help_text='Si tiene valor, el registro está soft-deleted', null=True, verbose_name='Fecha de eliminación')),
                ('estado', models.CharField(default='activo', help_text='Estado del vendedor: activo, inactivo, suspendido', max_length=50, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('promotor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendedores', to='usuarios.promotor', verbose_name='Promotor')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_vendedor', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Vendedor',
                'verbose_name_plural': 'Vendedores',
                'db_table': 'vendedores',
            },
        ),
        migrations.CreateModel(
            name='Verificador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, help_text='Si tiene valor, el registro está soft-deleted', null=True, verbose_name='Fecha de eliminación')),
                ('pago', models.DecimalField(decimal_places=2, help_text='Monto de pago al verificador', max_digits=10, verbose_name='Pago')),
                ('estado', models.CharField(default='activo', help_text='Estado del verificador: activo, inactivo, suspendido', max_length=50, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_verificador', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Verificador',
                'verbose_name_plural': 'Verificadores',
                'db_table': 'verificadores',
            },
        ),
    ]
