# Generated by Django 5.0.3 on 2026-06-12 21:50

import usuarios.models.usuario
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='foto',
            field=models.ImageField(blank=True, help_text='Avatar del usuario. Se guarda en media/usuarios/fotos/ o en MinIO/S3.', null=True, upload_to=usuarios.models.usuario.usuario_foto_upload_path, verbose_name='Foto de perfil'),
        ),
    ]
