# Generated by Django 5.0.3 on 2026-03-29 01:37

import django.db.models.deletion
import django.utils.timezone
import usuarios.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, help_text='Si tiene valor, el registro está soft-deleted', null=True, verbose_name='Fecha de eliminación')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre completo')),
                ('ci', models.CharField(max_length=20, unique=True, verbose_name='Cédula de identidad')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Persona',
                'verbose_name_plural': 'Personas',
                'db_table': 'personas',
            },
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={'permissions': [('gestionar_eventos', 'Puede crear, editar y eliminar eventos'), ('verificar_tickets', 'Puede escanear y verificar tickets en el acceso'), ('gestionar_artistas', 'Puede administrar perfiles de artistas'), ('ver_reportes', 'Puede ver reportes financieros y de ventas')], 'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.AlterModelManagers(
            name='usuario',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='telefono',
        ),
        migrations.AddField(
            model_name='usuario',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='deleted_at',
            field=models.DateTimeField(blank=True, default=None, help_text='Si tiene valor, el registro está soft-deleted', null=True, verbose_name='Fecha de eliminación'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Correo electrónico'),
        ),
        migrations.AlterModelTable(
            name='usuario',
            table='usuarios',
        ),
        migrations.CreateModel(
            name='Artista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, help_text='Si tiene valor, el registro está soft-deleted', null=True, verbose_name='Fecha de eliminación')),
                ('nombre_artistico', models.CharField(max_length=255, verbose_name='Nombre artístico')),
                ('biografia', models.TextField(blank=True, null=True, verbose_name='Biografía')),
                ('foto', models.ImageField(blank=True, help_text='Imagen de perfil del artista. Se guarda en media/artistas/fotos/', null=True, upload_to=usuarios.models.artista_foto_upload_path, verbose_name='Foto del artista')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('generos_musicales', models.ManyToManyField(blank=True, db_table='artista_genero_musical', related_name='artistas', to='eventos.generomusical', verbose_name='Géneros musicales')),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perfil_artista', to=settings.AUTH_USER_MODEL, verbose_name='Usuario vinculado')),
            ],
            options={
                'verbose_name': 'Artista',
                'verbose_name_plural': 'Artistas',
                'db_table': 'artistas',
            },
        ),
        migrations.CreateModel(
            name='Organizador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, help_text='Si tiene valor, el registro está soft-deleted', null=True, verbose_name='Fecha de eliminación')),
                ('razon_social', models.CharField(max_length=255, verbose_name='Razón social')),
                ('nit_rfc', models.CharField(max_length=50, verbose_name='NIT/RFC')),
                ('banco_nombre', models.CharField(max_length=100, verbose_name='Nombre del banco')),
                ('cuenta_bancaria', models.CharField(max_length=50, verbose_name='Cuenta bancaria')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_organizador', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Organizador',
                'verbose_name_plural': 'Organizadores',
                'db_table': 'organizadores',
            },
        ),
        migrations.AddField(
            model_name='usuario',
            name='persona',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuario', to='usuarios.persona', verbose_name='Persona'),
        ),
        migrations.CreateModel(
            name='Verificador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, help_text='Si tiene valor, el registro está soft-deleted', null=True, verbose_name='Fecha de eliminación')),
                ('pago', models.DecimalField(decimal_places=2, help_text='Monto de pago al verificador', max_digits=10, verbose_name='Pago')),
                ('estado', models.CharField(default='activo', help_text='Estado del verificador: activo, inactivo, suspendido', max_length=50, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_verificador', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Verificador',
                'verbose_name_plural': 'Verificadores',
                'db_table': 'verificadores',
            },
        ),
    ]
