# Generated by Django 5.0.3 on 2026-06-14 01:37

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0002_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artista',
            name='departamento_origen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='artistas_origen', to='eventos.departamento', verbose_name='Departamento de origen'),
        ),
        migrations.AddField(
            model_name='artista',
            name='popularidad',
            field=models.IntegerField(default=0, help_text='Popularidad del artista de 0 a 100', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Popularidad'),
        ),
    ]
