# Generated by Django 5.0.3 on 2026-06-20 00:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0002_initial'),
        ('usuarios', '0002_artista_departamento_origen_artista_popularidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='recibir_notificaciones',
            field=models.BooleanField(default=True, help_text='Permite habilitar o deshabilitar la recepción de notificaciones en el sistema.', verbose_name='Recibir notificaciones'),
        ),
        migrations.CreateModel(
            name='DispositivoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fcm_token', models.TextField(unique=True, verbose_name='Token FCM')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispositivos', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Dispositivo de Usuario',
                'verbose_name_plural': 'Dispositivos de Usuarios',
                'db_table': 'dispositivos_usuario',
            },
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título')),
                ('mensaje', models.TextField(verbose_name='Mensaje')),
                ('tipo', models.CharField(choices=[('nuevo_evento', 'Nuevo Evento Publicado'), ('evento_artista', 'Artista Incluido en Evento')], max_length=50, verbose_name='Tipo')),
                ('leido', models.BooleanField(default=False, verbose_name='Leído')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('evento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='eventos.evento', verbose_name='Evento')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'db_table': 'notificaciones',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SeguidorPromotor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('promotor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguidores', to='usuarios.promotor', verbose_name='Promotor')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguimientos_promotores', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Seguidor de Promotor',
                'verbose_name_plural': 'Seguidores de Promotores',
                'db_table': 'seguidores_promotores',
                'unique_together': {('usuario', 'promotor')},
            },
        ),
    ]
