# Generated by Django 5.0.3 on 2026-06-21 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_alter_notificacion_tipo_amistad'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificador',
            name='promotor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='verificadores', to='usuarios.promotor', verbose_name='Promotor'),
        ),
        migrations.AlterField(
            model_name='verificador',
            name='pago',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Monto de pago al verificador', max_digits=10, verbose_name='Pago'),
        ),
        migrations.DeleteModel(
            name='Vendedor',
        ),
    ]
