# Generated by Django 5.0.3 on 2026-06-13 22:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eventos', '0001_initial'),
        ('tickets', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='promotor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eventos', to='usuarios.promotor', verbose_name='Promotor'),
        ),
        migrations.AddField(
            model_name='lugar',
            name='departamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lugares', to='eventos.departamento', verbose_name='Departamento'),
        ),
        migrations.AddField(
            model_name='evento',
            name='lugar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eventos', to='eventos.lugar', verbose_name='Lugar'),
        ),
        migrations.AddField(
            model_name='presentacionevento',
            name='artista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presentaciones', to='usuarios.artista', verbose_name='Artista'),
        ),
        migrations.AddField(
            model_name='presentacionevento',
            name='evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presentaciones', to='eventos.evento', verbose_name='Evento'),
        ),
        migrations.AddField(
            model_name='registroacceso',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_acceso', to='tickets.ticket', verbose_name='Ticket'),
        ),
        migrations.AddField(
            model_name='verificadorevento',
            name='evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verificadores_evento', to='eventos.evento', verbose_name='Evento'),
        ),
        migrations.AddField(
            model_name='verificadorevento',
            name='verificador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos_asignados', to='usuarios.verificador', verbose_name='Verificador'),
        ),
        migrations.AddField(
            model_name='registroacceso',
            name='verificador_evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_acceso', to='eventos.verificadorevento', verbose_name='Verificador del evento'),
        ),
        migrations.AddField(
            model_name='zona',
            name='evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zonas', to='eventos.evento', verbose_name='Evento'),
        ),
        migrations.AddField(
            model_name='asiento',
            name='zona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asientos', to='eventos.zona', verbose_name='Zona'),
        ),
        migrations.AlterUniqueTogether(
            name='verificadorevento',
            unique_together={('evento', 'verificador')},
        ),
        migrations.AlterUniqueTogether(
            name='asiento',
            unique_together={('fila', 'columna', 'zona')},
        ),
    ]
