# Generated by Django 5.0.3 on 2026-03-29 01:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eventos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, help_text='Si tiene valor, el registro está soft-deleted', null=True, verbose_name='Fecha de eliminación')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio total')),
                ('estado_pago', models.CharField(default='pendiente', help_text='pendiente, pagado, reembolsado, cancelado', max_length=50, verbose_name='Estado del pago')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='facturas', to=settings.AUTH_USER_MODEL, verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Factura',
                'verbose_name_plural': 'Facturas',
                'db_table': 'facturas',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, help_text='Si tiene valor, el registro está soft-deleted', null=True, verbose_name='Fecha de eliminación')),
                ('codigo_qr', models.CharField(help_text='Código único para validación del ticket', max_length=255, unique=True, verbose_name='Código QR')),
                ('estado', models.CharField(default='activo', help_text='activo, usado, cancelado, expirado', max_length=50, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asiento', models.OneToOneField(blank=True, help_text='NULL si la zona no es numerada', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket', to='eventos.asiento', verbose_name='Asiento')),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='tickets.factura', verbose_name='Factura')),
                ('zona', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='eventos.zona', verbose_name='Zona')),
            ],
            options={
                'verbose_name': 'Ticket',
                'verbose_name_plural': 'Tickets',
                'db_table': 'tickets',
            },
        ),
    ]
