# Generated by Django 5.0.3 on 2026-06-13 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, help_text='Si tiene valor, el registro está soft-deleted', null=True, verbose_name='Fecha de eliminación')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio total')),
                ('estado_pago', models.CharField(default='pendiente', help_text='pendiente, pagado, reembolsado, cancelado', max_length=50, verbose_name='Estado del pago')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Factura',
                'verbose_name_plural': 'Facturas',
                'db_table': 'facturas',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, help_text='Si tiene valor, el registro está soft-deleted', null=True, verbose_name='Fecha de eliminación')),
                ('codigo_qr', models.CharField(help_text='Código único para validación del ticket', max_length=255, unique=True, verbose_name='Código QR')),
                ('estado', models.CharField(default='activo', help_text='activo, usado, cancelado, expirado', max_length=50, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ticket',
                'verbose_name_plural': 'Tickets',
                'db_table': 'tickets',
            },
        ),
    ]
