# Generated by Django 5.0.3 on 2026-06-13 22:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eventos', '0002_initial'),
        ('tickets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='facturas', to=settings.AUTH_USER_MODEL, verbose_name='Cliente'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='asiento',
            field=models.OneToOneField(blank=True, help_text='NULL si la zona no es numerada', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket', to='eventos.asiento', verbose_name='Asiento'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='factura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='tickets.factura', verbose_name='Factura'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='zona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='eventos.zona', verbose_name='Zona'),
        ),
    ]
