# Generated by Django 5.0.3 on 2026-06-14 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='stripe_payment_intent_id',
            field=models.CharField(blank=True, help_text='ID del PaymentIntent de Stripe para trazabilidad', max_length=255, null=True, verbose_name='Stripe PaymentIntent ID'),
        ),
    ]
