# Generated by Django 5.0.3 on 2026-06-21 14:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_factura_stripe_payment_intent_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='propietario',
            field=models.ForeignKey(blank=True, help_text='Usuario que posee actualmente el ticket (puede diferir del comprador tras transferencia)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tickets_propios', to=settings.AUTH_USER_MODEL, verbose_name='Propietario actual'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='transferido',
            field=models.BooleanField(default=False, help_text='Solo se permite una transferencia por ticket', verbose_name='Ya transferido'),
        ),
        migrations.CreateModel(
            name='TransferenciaTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transferencias_recibidas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario destino')),
                ('origen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transferencias_enviadas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario origen')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transferencias', to='tickets.ticket', verbose_name='Ticket')),
            ],
            options={
                'verbose_name': 'Transferencia de Ticket',
                'verbose_name_plural': 'Transferencias de Tickets',
                'db_table': 'transferencias_tickets',
                'ordering': ['-created_at'],
            },
        ),
    ]
